In [6]:
import duckdb
import numpy as np
import pandas as pd
from datetime import datetime
import csv

In [7]:
LIMIT = 1000

In [8]:
conn = duckdb.connect()
ship_data = conn.execute(f"""
    SELECT * FROM read_csv_auto("../../../aisdk-2025-02-28.csv") LIMIT {LIMIT}              
""").df()

ship_data
       
    # write to csv file

,# Timestamp,Type of mobile,MMSI,Latitude,Longitude,Navigational status,ROT,SOG,COG,Heading,...,Length,Type of position fixing device,Draught,Destination,ETA,Data source type,A,B,C,D
0,2025-02-28 00:00:00,Class A,266239000,54.609702,13.715475,Under way using engine,0.0,17.0,328.3,329,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
1,2025-02-28 00:00:00,Base Station,2190064,56.716567,11.519037,Unknown value,NaN,NaN,NaN,<NA>,...,<NA>,GPS,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
2,2025-02-28 00:00:00,Class A,219002136,57.182753,8.523752,Engaged in fishing,NaN,8.2,147.2,153,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
3,2025-02-28 00:00:00,Class A,219002136,57.182753,8.523752,Engaged in fishing,NaN,8.2,147.2,153,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
4,2025-02-28 00:00:00,Base Station,2194006,55.538870,5.033200,Unknown value,NaN,NaN,NaN,<NA>,...,<NA>,Surveyed,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2025-02-28 00:00:04,Class A,219024715,57.492593,10.504980,Engaged in fishing,0.0,0.0,NaN,237,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
996,2025-02-28 00:00:04,Class A,257980000,55.466715,10.528507,Under way sailing,0.0,0.0,230.5,216,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
997,2025-02-28 00:00:04,Class A,219006283,56.764297,8.863188,Unknown value,NaN,0.0,96.8,<NA>,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
998,2025-02-28 00:00:04,Class A,219022903,56.152152,10.254583,Reserved for future amendment [HSC],0.0,0.0,205.4,24,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
999,2025-02-28 00:00:04,Class A,219022000,57.121628,8.598483,Engaged in fishing,0.0,0.0,258.3,330,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>

In [9]:
ship_data.shape

(1000, 26)

In [10]:
ship_data.columns

Index(['# Timestamp', 'Type of mobile', 'MMSI', 'Latitude', 'Longitude',
       'Navigational status', 'ROT', 'SOG', 'COG', 'Heading', 'IMO',
       'Callsign', 'Name', 'Ship type', 'Cargo type', 'Width', 'Length',
       'Type of position fixing device', 'Draught', 'Destination', 'ETA',
       'Data source type', 'A', 'B', 'C', 'D'],
      dtype='str')

In [11]:
# TODO:
# Perform anomaly detetion tasks
ship_data.dropna()

,# Timestamp,Type of mobile,MMSI,Latitude,Longitude,Navigational status,ROT,SOG,COG,Heading,...,Length,Type of position fixing device,Draught,Destination,ETA,Data source type,A,B,C,D
460,2025-02-28 00:00:02,Class A,212900000,56.156172,12.413825,Under way using engine,0.0,9.7,128.0,126,...,88,GPS,3.1,SEMMA,2025-02-28 05:00:00,AIS,77,11,8,5
461,2025-02-28 00:00:02,Class A,212900000,56.156172,12.413825,Under way using engine,0.0,9.7,128.0,126,...,88,GPS,3.1,SEMMA,2025-02-28 05:00:00,AIS,77,11,8,5
472,2025-02-28 00:00:02,Class A,219001431,54.999220,9.671183,Under way using engine,0.0,0.0,230.8,50,...,40,GPS,2.0,BALLEBRO - HARDESHOJ,2025-03-17 18:00:00,AIS,20,20,7,5

In [12]:
np.unique(ship_data[ship_data["Type of mobile"] == "Class A"]["# Timestamp"])

array(['2025-02-28T00:00:00.000000', '2025-02-28T00:00:01.000000',
       '2025-02-28T00:00:02.000000', '2025-02-28T00:00:03.000000',
       '2025-02-28T00:00:04.000000'], dtype='datetime64[us]')

In [13]:
np.unique(ship_data[ship_data["Type of mobile"] == "Class A"]["# Timestamp"])

array(['2025-02-28T00:00:00.000000', '2025-02-28T00:00:01.000000',
       '2025-02-28T00:00:02.000000', '2025-02-28T00:00:03.000000',
       '2025-02-28T00:00:04.000000'], dtype='datetime64[us]')

In [14]:
np.unique(ship_data["MMSI"])

array([     3638,   2190047,   2190048,   2190052,   2190064,   2190065,
         2190066,   2190067,   2190068,   2190069,   2190071,   2190073,
         2190074,   2190076,   2190077,   2194005,   2194006,   2194016,
         2573115,   2573125,   2573135,   2573145,   2655130,   2655135,
         2655140,   2655146,   2655148,   2655150,   2655185, 205210000,
       209336000, 209531000, 209974000, 210046000, 210071000, 210144000,
       210359000, 210399000, 211169660, 211188000, 211190000, 211209290,
       211282410, 211291160, 211325200, 211364330, 211410690, 211493380,
       211543450, 211731030, 211736820, 211757470, 211833390, 211866190,
       211870240, 212613000, 212797000, 212801000, 212880000, 212882000,
       212900000, 215116000, 215195000, 215489000, 218000630, 218005000,
       218041490, 218085000, 218413000, 218601000, 218805000, 218816000,
       219000187, 219000245, 219000368, 219000431, 219000577, 219000604,
       219000617, 219000647, 219000751, 219000771, 219000781, 219000804,
       219000811, 219000818, 219000872, 219000881, 219000892, 219000897,
       219000942, 219001083, 219001149, 219001262, 219001265, 219001266,
       219001343, 219001431, 219001518, 219001587, 219001654, 219001682,
       219001695, 219001771, 219001819, 219001849, 219001959, 219002136,
       219002358, 219002418, 219002585, 219002602, 219002774, 219002798,
       219002801, 219002827, 219002838, 219003103, 219003141, 219003369,
       219003383, 219003966, 219004043, 219004128, 219004279, 219004473,
       219004596, 219005453, 219005496, 219005513, 219005732, 219005826,
       219005867, 219005886, 219005929, 219005954, 219005956, 219005969,
       219006091, 219006092, 219006113, 219006283, 219006284, 219006301,
       219006304, 219006382, 219006598, 219006835, 219006971, 219007036,
       219007155, 219007314, 219007366, 219007393, 219007457, 219007596,
       219007705, 219007937, 219008089, 219009135, 219009229, 219010207,
       219010518, 219010873, 219011021, 219011032, 219011225, 219011491,
       219012076, 219012521, 219013178, 219013192, 219013667, 219013753,
       219013964, 219014161, 219014162, 219014851, 219014974, 219015233,
       219015332, 219015338, 219015425, 219016663, 219016689, 219016747,
       219016759, 219016873, 219016938, 219017664, 219017895, 219017896,
       219017917, 219018172, 219018486, 219018488, 219018493, 219019219,
       219019804, 219019852, 219019887, 219020187, 219020188, 219020398,
       219020578, 219021176, 219021244, 219021266, 219021300, 219021428,
       219022000, 219022047, 219022257, 219022260, 219022267, 219022903,
       219023274, 219023313, 219023588, 219023691, 219023834, 219024175,
       219024176, 219024178, 219024281, 219024402, 219024524, 219024675,
       219024676, 219024702, 219024715, 219024783, 219024784, 219024915,
       219025072, 219025528, 219025739, 219026000, 219026147, 219026170,
       219026172, 219026257, 219026443, 219026675, 219026706, 219027026,
       219027308, 219027309, 219027804, 219027899, 219027992, 219028043,
       219028267, 219028337, 219028501, 219028794, 219029233, 219029576,
       219029698, 219029706, 219029751, 219030200, 219030406, 219030452,
       219030656, 219030764, 219031428, 219031429, 219031645, 219032650,
       219032845, 219032869, 219033013, 219033720, 219106000, 219186000,
       219230000, 219250000, 219313000, 219329000, 219330000, 219385000,
       219423000, 219435000, 219438000, 219449000, 219461000, 219560000,
       219570000, 219592000, 219705000, 219786000, 219793000, 219796000,
       219801000, 219862000, 219868000, 219872000, 219921000, 219945000,
       219948000, 219959000, 219965000, 220024000, 220043000, 220076000,
       220135000, 220191000, 220205000, 220228000, 220257000, 220272000,
       220278000, 220279000, 220283000, 220304000, 220307000, 220323000,
       220329000, 220334000, 220336000, 220339000, 220341000, 220345000,
       220352000, 220432000, 220446000, 220476000, 220490000, 220507000,
       220544000, 220622000, 228468600, 230039000, 230179120, 230617000,
       230712000, 230941700, 231048000, 231336000, 231355000, 231613000,
       232008636, 232025009, 232025959, 232046826, 235003400, 235007573,
       235007860, 235112981, 235500000, 238056000, 238265000, 240168000,
       244017000, 244110823, 244140000, 244267000, 244321000, 244641000,
       244710825, 244750595, 244780097, 244790715, 245043000, 245241000,
       245250000, 245281000, 245286000, 245313000, 245618000, 245808000,
       245809000, 245918000, 246058000, 246135000, 246389000, 246443000,
       246607000, 246702000, 246818000, 246855000, 246925000, 246970000,
       247153600, 247389200, 248789000, 248886000, 248891000, 248971000,
       249127000, 255769000, 255801580, 255805589, 255806310, 255806457,
       255808000, 255814000, 255815000, 255915649, 255915668, 255915769,
       255915940, 255915985, 256591000, 256683000, 257058070, 257101030,
       257207000, 257286400, 257339000, 257341000, 257461000, 257574500,
       257643000, 257736000, 257898920, 257900000, 257959000, 257964000,
       257980000, 257986000, 258059000, 258313000, 259040100, 259222000,
       261002720, 261003244, 261004060, 265011730, 265026000, 265031000,
       265042000, 265047000, 265049000, 265051000, 265060520, 265410000,
       265412000, 265463000, 265509950, 265511440, 265513470, 265518160,
       265522210, 265522220, 265522240, 265523410, 265527470, 265573140,
       265595430, 265610950, 265621060, 265675230, 265695200, 265703000,
       265704020, 265705100, 265725520, 265754000, 265754450, 265768860,
       265859000, 265866000, 265960000, 266076000, 266143000, 266239000,
       266319000, 266331000, 266343000, 266394000, 266465000, 273257120,
       273376490, 275510000, 275511000, 277334000, 277391000, 277399000,
       305299000, 305414000, 305937000, 305981000, 309924000, 311001499,
       311027400, 311831000, 314608000, 314986000, 331100197, 331184000,
       352001751, 352002241, 352002621, 352004805, 355390000, 357100000,
       372837000, 413702170, 511101557, 518999464, 525008075, 538005194,
       538007007, 538007403, 538008717, 538010222, 538010659, 566954000,
       621819095, 630001114, 636015378, 636015461, 636017073, 636017570,
       636020206, 636020544, 636021728, 636021768, 636022640, 636022830,
       636023238, 636023684, 636023944, 636024847, 636092706, 636093238,
       667002396, 668116152, 668116306, 668116311, 918000125, 992111701,
       992111703, 992111704, 992111761, 992111762, 992111797, 992111840,
       992111841, 992111842, 992111888, 992111924, 992111926, 992111927,
       992576507])

In [15]:
ship_data[ship_data["MMSI"] == 3638]

,# Timestamp,Type of mobile,MMSI,Latitude,Longitude,Navigational status,ROT,SOG,COG,Heading,...,Length,Type of position fixing device,Draught,Destination,ETA,Data source type,A,B,C,D
321,2025-02-28 00:00:01,Class A,3638,91.0,0.0,Unknown value,NaN,NaN,NaN,<NA>,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
323,2025-02-28 00:00:01,Class A,3638,91.0,0.0,Unknown value,NaN,NaN,NaN,<NA>,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
326,2025-02-28 00:00:01,Class A,3638,91.0,0.0,Unknown value,NaN,NaN,NaN,<NA>,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
327,2025-02-28 00:00:01,Class A,3638,91.0,0.0,Unknown value,NaN,NaN,NaN,<NA>,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
328,2025-02-28 00:00:01,Class A,3638,91.0,0.0,Unknown value,NaN,NaN,NaN,<NA>,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>
330,2025-02-28 00:00:01,Class A,3638,91.0,0.0,Unknown value,NaN,NaN,NaN,<NA>,...,<NA>,Undefined,NaN,Unknown,NaT,AIS,<NA>,<NA>,<NA>,<NA>

In [16]:
ship_data.dtypes

# Timestamp                       datetime64[us]
Type of mobile                               str
MMSI                                       int64
Latitude                                 float64
Longitude                                float64
Navigational status                          str
ROT                                      float64
SOG                                      float64
COG                                      float64
Heading                                    Int64
IMO                                          str
Callsign                                     str
Name                                         str
Ship type                                    str
Cargo type                                   str
Width                                      Int64
Length                                     Int64
Type of position fixing device               str
Draught                                  float64
Destination                                  str
ETA                               datetime64[us]
Data source type                             str
A                                          Int64
B                                          Int64
C                                          Int64
D                                          Int64
dtype: object

In [20]:
ship_data[["Draught"]].dropna()

     Draught
147      5.5
170      5.2
296      2.5
349      3.0
452      2.5
457      2.5
460      3.1
461      3.1
472      2.0
520      9.1
521      9.1
543      2.5
544      2.5
552      6.3
553      2.5
611      1.5
612      1.5
613      2.0
614      1.5
638      2.5
682      5.2
685      5.2
710      3.0
750      3.4
752      3.4
765      4.5
766      4.5
767      5.5
768      4.5
769      5.5
788      5.4
792      3.3
793      5.4
844      2.5
850      2.5
939      2.5
946      3.0